### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by wwj718** [CodeLabClub/scratch3_faceapi_install#1]
建议放出积木预览与一些小案例，可以参考[ml2scratch](https://github.com/champierre/ml2scratch)

**Comment by mickwubs97** [comment]
OK，knn的部分我已经加了三个gif上去，之后会有一个一分钟的视频，包括“石头剪刀布”的训练和验证过程，之后尝试一些其他日常物品的识别。目前这个repo我在尝试加一个更加详尽的介绍（recognition branch）,所以可能更新会相对慢一点，希望理解。

谢谢您的反馈，欢迎您提出进一步的意见。

**Comment by wwj718** [comment]
太棒了👍
